name: Buzz
favicon: null
layout_spectrum: 0.20881
typography_spectrum: 0.3869173468556255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4375
  lightness: 0.7596327334176749
  saturation: 0.7341122978832573
  rhythmicContrast: 0.42734336433932185
purpose: []
